### ISSUE TITLE
How to build multipart/form-data

### ISSUE THREAD

**Issue by khaiphan9x** [hollodotme/fast-cgi-client#53]
I want to create a file upload using FastCGI Client, it seems that it only supports STDIN as normal POST

**Comment by hollodotme** [comment]
Hi @khaiphan9x! Thanks for your question.

In order to place a multipart/form-data request including file upload there are the following things to do:

1. Define a boundary identifier, e.g. `__X_FASTCGI_CLIENT_BOUNDARY__`
2. Set the `Content-Type` header of the POST request  to `multipart/form-data; boundary=__X_FASTCGI_CLIENT_BOUNDARY__`
3. Compose the content for the POST request with the parts you want to transfer (POST data and FILES). For example if you want to send the data `test="some data"` and the file with key `testFile` at `/path/to/testFile.txt` the content must look like this:

```
--__X_FASTCGI_CLIENT_BOUNDARY__
Content-Disposition: form-data; name="test"
some data
--__X_FASTCGI_CLIENT_BOUNDARY__
Content-Disposition: form-data; name="testFile"; filename="testFile.txt"
Content-Type: application/octet-stream"
Content-Transfer-Encoding: base64

[BASE64_ENCODED_CONTENT_OF_FILE]
--__X_FASTCGI_CLIENT_BOUNDARY__--

```

Please have a look into the development branch where I wrote: 
* a `MultipartFormData` class that composes the content based on a data and a file array, [see here](https://github.com/hollodotme/fast-cgi-client/blob/development/src/RequestContents/MultipartFormData.php)
* a test that uploads the file using the FastCGI client to a script, see [test here](https://github.com/hollodotme/fast-cgi-client/blob/development/tests/Integration/FileUploadTest.php) and [script here](https://github.com/hollodotme/fast-cgi-client/blob/development/tests/Integration/Workers/fileUploadWorker.php)

Please note that you have to do the request / content composition by hand with the current stable release. I plan to integrate the aforementioned content provider into the next release.

I hope this helps.

**Comment by khaiphan9x** [comment]
> Hi @khaiphan9x! Thanks for your question.
> 
> In order to place a multipart/form-data request including file upload there are the following things to do:
> 
> 1. Define a boundary identifier, e.g. `__X_FASTCGI_CLIENT_BOUNDARY__`
> 2. Set the `Content-Type` header of the POST request  to `multipart/form-data; boundary=__X_FASTCGI_CLIENT_BOUNDARY__`
> 3. Compose the content for the POST request with the parts you want to transfer (POST data and FILES). For example if you want to send the data `test="some data"` and the file with key `testFile` at `/path/to/testFile.txt` the content must look like this:
> 
> ```
> --__X_FASTCGI_CLIENT_BOUNDARY__
> Content-Disposition: form-data; name="test"
> 
> some data
> --__X_FASTCGI_CLIENT_BOUNDARY__
> Content-Disposition: form-data; name="testFile"; filename="testFile.txt"
> Content-Type: application/octet-stream"
> Content-Transfer-Encoding: base64
> 
> [BASE64_ENCODED_CONTENT_OF_FILE]
> --__X_FASTCGI_CLIENT_BOUNDARY__--
> ```
> 
> Please have a look into the development branch where I wrote:
> 
> * a `MultipartFormData` class that composes the content based on a data and a file array, [see here](https://github.com/hollodotme/fast-cgi-client/blob/development/src/RequestContents/MultipartFormData.php)
> * a test that uploads the file using the FastCGI client to a script, see [test here](https://github.com/hollodotme/fast-cgi-client/blob/development/tests/Integration/FileUploadTest.php) and [script here](https://github.com/hollodotme/fast-cgi-client/blob/development/tests/Integration/Workers/fileUploadWorker.php)
> 
> Please note that you have to do the request / content composition by hand with the current stable release. I plan to integrate the aforementioned content provider into the next release.
> 
> I hope this helps.

It will be easier to understand if you write a sample PHP, thank you!

**Comment by khaiphan9x** [comment]
> Hi @khaiphan9x! Thanks for your question.
> 
> In order to place a multipart/form-data request including file upload there are the following things to do:
> 
> 1. Define a boundary identifier, e.g. `__X_FASTCGI_CLIENT_BOUNDARY__`
> 2. Set the `Content-Type` header of the POST request  to `multipart/form-data; boundary=__X_FASTCGI_CLIENT_BOUNDARY__`
> 3. Compose the content for the POST request with the parts you want to transfer (POST data and FILES). For example if you want to send the data `test="some data"` and the file with key `testFile` at `/path/to/testFile.txt` the content must look like this:
> 
> ```
> --__X_FASTCGI_CLIENT_BOUNDARY__
> Content-Disposition: form-data; name="test"
> 
> some data
> --__X_FASTCGI_CLIENT_BOUNDARY__
> Content-Disposition: form-data; name="testFile"; filename="testFile.txt"
> Content-Type: application/octet-stream"
> Content-Transfer-Encoding: base64
> 
> [BASE64_ENCODED_CONTENT_OF_FILE]
> --__X_FASTCGI_CLIENT_BOUNDARY__--
> ```
> 
> Please have a look into the development branch where I wrote:
> 
> * a `MultipartFormData` class that composes the content based on a data and a file array, [see here](https://github.com/hollodotme/fast-cgi-client/blob/development/src/RequestContents/MultipartFormData.php)
> * a test that uploads the file using the FastCGI client to a script, see [test here](https://github.com/hollodotme/fast-cgi-client/blob/development/tests/Integration/FileUploadTest.php) and [script here](https://github.com/hollodotme/fast-cgi-client/blob/development/tests/Integration/Workers/fileUploadWorker.php)
> 
> Please note that you have to do the request / content composition by hand with the current stable release. I plan to integrate the aforementioned content provider into the next release.
> 
> I hope this helps.

I hope it comes soon, with an easy-to-use sample code
I can set boundary as I like
