### ISSUE TITLE
access socket id

### ISSUE THREAD

**Issue by oceanimagine** [hollodotme/fast-cgi-client#67]
hi, i really want to know how to access `socket id` that i get from Fire And Forget script to another file, i assume if `socket id` already got then we can use it to another file, i really sorry for bad english, i will give you the chronology 

so i made a php script from Fire And Forget example, here the script

```
<?php declare(strict_types=1);

namespace LEARNING\LEARNING;
require __DIR__ . '/vendor/autoload.php';

use hollodotme\FastCGI\Client;
use hollodotme\FastCGI\Requests\PostRequest;
use hollodotme\FastCGI\SocketConnections\NetworkSocket;
use hollodotme\FastCGI\SocketConnections\UnixDomainSocket;
$client     = new Client();
$connection = new UnixDomainSocket('/var/run/php/php7.1-fpm.sock', 5000, 5000);
$content    = http_build_query(['key' => 'value']);
$request    = new PostRequest('/var/www/html/async-php/ulang.php', $content);

$socketId = $client->sendAsyncRequest($connection, $request);

echo "Request sent, got ID: {$socketId}\n";
```

and then i get the `socket id` it self, but i assume that i can used the `socket id` to another file, here a script that i use 

```
<?php declare(strict_types=1);

namespace LEARNING\LEARNING;
require __DIR__ . '/vendor/autoload.php';

use hollodotme\FastCGI\SocketConnections\UnixDomainSocket;
use hollodotme\FastCGI\Client;
use hollodotme\FastCGI\Requests\PostRequest;
use hollodotme\FastCGI\Interfaces\ProvidesResponseData;
use hollodotme\FastCGI\SocketConnections\NetworkSocket;
use Throwable;

$client     = new Client();
$connection = new UnixDomainSocket('/var/run/php/php7.1-fpm.sock', 5000, 5000);

while (true)
{
        $requestId = 445; # this is the 'socket id' that i got from first script
        if ($client->hasResponse($requestId))
        {
                $client->handleResponse($requestId);
                break;
        }
}
```

why i get error that said `socket id not found` ?
what exactly i missed ?
thanks in advance

**Comment by oceanimagine** [comment]
what if I want to see if the process is still running or not ?

**Comment by hollodotme** [comment]
@oceanimagine Please do not confuse request & response with processes. 

The client lets you send a request to a service (php-fpm) and you can check if the service has answered your request with a response.

You can do so by checking if a specific request has a response:

```php
if ( $client->hasResponse( $socketId ) )
{
    $response = $client->readResponse( $socketId );
}
```

or if the service has any unhandled responses:

```php
# Loop until all responses were received
while ( $client->hasUnhandledResponses() )
{
	# read all ready responses
	foreach ( $client->readReadyResponses( 3000 ) as $response )
	{
		echo $response->getBody() . "\n";
	}
	
	echo '.';
}

# ... is the same as

while ( $client->hasUnhandledResponses() )
{
	$readySocketIds = $client->getSocketIdsHavingResponse();
	
	# read all ready responses
	foreach ( $client->readResponses( 3000, ...$readySocketIds ) as $response )
	{
		echo $response->getBody() . "\n";
	}
	
	echo '.';
}

# ... is the same as

while ( $client->hasUnhandledResponses() )
{
	$readySocketIds = $client->getSocketIdsHavingResponse();
	
	# read all ready responses
	foreach ($readySocketIds as $socketId)
	{
		$response = $client->readResponse($socketId, 3000);
		echo $response->getBody() . "\n";
	}
	
	echo '.';
}
```

See documentation here: https://github.com/hollodotme/fast-cgi-client#sending-multiple-requests-and-reading-their-responses-reactive

Again, this only works in the same PHP request.

With the client you can **NOT** check if the service (php-fpm) has started a separate process for your request or reused an idle process. That heavily depends on your configuration of PHP-FPM. Nor can you check if the service has running processes. In order to do that you would have to check the service's status itself whereever it is running.

I did this for demonstration here: https://github.com/hollodotme/fast-cgi-client-demo/blob/master/public/showProcesses.php - But this has nothing to do with the fast-cgi-client itself.

**Comment by oceanimagine** [comment]
ok @hollodotme i will try my best to understand the concept about `request & response with processes` .
thanks a lot @hollodotme and of course i will use your library for async background process.

**Comment by hollodotme** [comment]
@oceanimagine Feel free to raise your questions in the [discussions section of this repository](https://github.com/hollodotme/fast-cgi-client/discussions), if you need more help.
