### ISSUE TITLE
[Improvement] Replace fsockopen with stream_socket_client

### ISSUE THREAD

**Issue by mfuehrer82** [hollodotme/fast-cgi-client#9]
The stream extension has a lot more configuration options.

See further: 
http://php.net/manual/en/intro.stream.php

**Comment by hollodotme** [comment]
Seems this will lead to a little BC break as `stream_socket_client()` expects the remote socket address instead of just host and port which `fsockopen()` requires.

So I'll change the interface of `hollodotme\FastCGI\Interfaces\ConfiguresSocketConnection` from: 

```php
<?php declare(strict_types=1);

interface ConfiguresSocketConnection
{
	public function getHost() : string;

	public function getPort() : int;

	public function getConnectTimeout() : int;

	public function getReadWriteTimeout() : int;
}
```

to:

```php
<?php declare(strict_types=1);

interface ConfiguresSocketConnection
{
	public function getSocketAddress() : string;

	public function getConnectTimeout() : int;

	public function getReadWriteTimeout() : int;
}
```

Furthermore the remote socket address requires a transport protocol which is `tcp://` for network sockets and `unix://` for unix domain sockets. To make the first parameters of `NetworkSocket` and `UnixDomainSocket` constructors consistent, the transport protocol must be omitted in both cases. That means creating a `UnixDomainSocket` connection must be constructed like this:

```php
# Only the socket path must be passed
$connection = new UnixDomainSocket( '/var/run/php/php7.1-fpm.sock' );
```

Until now it was: 

```php
$connection = new UnixDomainSocket( 'unix:///var/run/php/php7.1-fpm.sock' );
```

The transport protocol will be statically added by the both connection classes.
